resolution = 0.125

[problem]
lib = "embedded.lua"
force = "force"
boundary = "solution"
slip = "slip"
solution = "solution"
lam = "lam"

[generate_mesh]
intercepts = [
    [-1, 0.5, 1],
    [-2, -1, 1, 2]
]
bcs = [
    [
        {bc = "n", plane = 0},
        {bc = "f", plane = 1, region = [1]},
        {bc = "n", plane = 2}
    ],
    [{bc = "d", plane = 0}, {bc = "d", plane = 3}]
]

