#include "MeshParserIntegrationPaths.h"
#include "doctest.h"
#include "io/GlobalSimplexMeshBuilder.h"
#include "io/MeshParser.h"
#include "mesh/GlobalSimplexMesh.h"

/*
We test the HDF5 and GMSH parsers by parsing the same mesh file in both formats and comparing the
resulting meshes. The test checks that the number of elements and facets match, and that the actual
elements and facets are identical (after sorting). This ensures that both parsers produce consistent
meshes from the same input data.

The two files are BP5 mesh files. The msh file is generated using GMSH v4.8.4 while the HDF5 file is
generated by converting the msh file generated by GMSH using
PUMGen(https://github.com/SeisSol/PUMGen). Both files are included in the test data repository.
*/

using namespace tndm;

static constexpr std::size_t D = 3;

static auto getParsedMesh(std::string const& fname) -> std::unique_ptr<GlobalSimplexMesh<D>> {
    GlobalSimplexMeshBuilder<D> builder;
    auto [parser, error] = MeshParser::createWithValidation<D>(fname, &builder);
    if (!parser) {
        throw std::runtime_error(error);
    }
    if (!parser->parseFile(fname)) {
        throw std::runtime_error(fname + "\n" + std::string(parser->getErrorMessage()));
    }
    return builder.create(MPI_COMM_SELF);
}

TEST_CASE("HDF5 and GMSH parsers produce equivalent meshes") {
    auto h5Mesh = getParsedMesh(tndm::test::H5MeshPath);
    auto mshMesh = getParsedMesh(tndm::test::MshMeshPath);

    auto h5Local = h5Mesh->getLocalMesh();
    auto mshLocal = mshMesh->getLocalMesh();

    SUBCASE("Element count matches") { CHECK(h5Mesh->numElements() == mshMesh->numElements()); }

    SUBCASE("Elements are identical") {
        auto h5Elems = h5Mesh->getElements();
        auto mshElems = mshMesh->getElements();
        std::sort(h5Elems.begin(), h5Elems.end());
        std::sort(mshElems.begin(), mshElems.end());
        CHECK(h5Elems == mshElems);
    }

    SUBCASE("Facet count matches") { CHECK(h5Local->numFacets() == mshLocal->numFacets()); }

    SUBCASE("Facets are identical") {
        auto h5Facets = h5Local->facets().faces();
        auto mshFacets = mshLocal->facets().faces();
        std::sort(h5Facets.begin(), h5Facets.end());
        std::sort(mshFacets.begin(), mshFacets.end());
        CHECK(h5Facets == mshFacets);
    }
}
