final_time = 63072000
mesh_file = "bp6_hf50.msh"
mode = "QDGreen"
type = "poisson"
lib = "bp6.lua"
scenario = "bp6"
ref_normal = [-1, 0]
boundary_linear = true

gf_checkpoint_prefix = "GreensFunctions/bp6_hf50"

[fault_output]
prefix = "outputs_S_50m/fault"
t_max = 3600
rtol = 0.1

[fault_probe_output]
prefix = "outputs_S_50m/fltst_strk"
t_max = 3600
rtol = 0.1
probes = [
    { name = "-200", x = [0.0, -20.0] },
    { name = "-199", x = [0.0, -19.9] },
    { name = "-198", x = [0.0, -19.8] },
    { name = "-197", x = [0.0, -19.7] },
    { name = "-196", x = [0.0, -19.6] },
    { name = "-195", x = [0.0, -19.5] },
    { name = "-194", x = [0.0, -19.4] },
    { name = "-193", x = [0.0, -19.3] },
    { name = "-192", x = [0.0, -19.2] },
    { name = "-191", x = [0.0, -19.1] },
    { name = "-190", x = [0.0, -19.0] },
    { name = "-189", x = [0.0, -18.9] },
    { name = "-188", x = [0.0, -18.8] },
    { name = "-187", x = [0.0, -18.7] },
    { name = "-186", x = [0.0, -18.6] },
    { name = "-185", x = [0.0, -18.5] },
    { name = "-184", x = [0.0, -18.4] },
    { name = "-183", x = [0.0, -18.3] },
    { name = "-182", x = [0.0, -18.2] },
    { name = "-181", x = [0.0, -18.1] },
    { name = "-180", x = [0.0, -18.0] },
    { name = "-179", x = [0.0, -17.9] },
    { name = "-178", x = [0.0, -17.8] },
    { name = "-177", x = [0.0, -17.7] },
    { name = "-176", x = [0.0, -17.6] },
    { name = "-175", x = [0.0, -17.5] },
    { name = "-174", x = [0.0, -17.4] },
    { name = "-173", x = [0.0, -17.3] },
    { name = "-172", x = [0.0, -17.2] },
    { name = "-171", x = [0.0, -17.1] },
    { name = "-170", x = [0.0, -17.0] },
    { name = "-169", x = [0.0, -16.9] },
    { name = "-168", x = [0.0, -16.8] },
    { name = "-167", x = [0.0, -16.7] },
    { name = "-166", x = [0.0, -16.6] },
    { name = "-165", x = [0.0, -16.5] },
    { name = "-164", x = [0.0, -16.4] },
    { name = "-163", x = [0.0, -16.3] },
    { name = "-162", x = [0.0, -16.2] },
    { name = "-161", x = [0.0, -16.1] },
    { name = "-160", x = [0.0, -16.0] },
    { name = "-159", x = [0.0, -15.9] },
    { name = "-158", x = [0.0, -15.8] },
    { name = "-157", x = [0.0, -15.7] },
    { name = "-156", x = [0.0, -15.6] },
    { name = "-155", x = [0.0, -15.5] },
    { name = "-154", x = [0.0, -15.4] },
    { name = "-153", x = [0.0, -15.3] },
    { name = "-152", x = [0.0, -15.2] },
    { name = "-151", x = [0.0, -15.1] },
    { name = "-150", x = [0.0, -15.0] },
    { name = "-149", x = [0.0, -14.9] },
    { name = "-148", x = [0.0, -14.8] },
    { name = "-147", x = [0.0, -14.7] },
    { name = "-146", x = [0.0, -14.6] },
    { name = "-145", x = [0.0, -14.5] },
    { name = "-144", x = [0.0, -14.4] },
    { name = "-143", x = [0.0, -14.3] },
    { name = "-142", x = [0.0, -14.2] },
    { name = "-141", x = [0.0, -14.1] },
    { name = "-140", x = [0.0, -14.0] },
    { name = "-139", x = [0.0, -13.9] },
    { name = "-138", x = [0.0, -13.8] },
    { name = "-137", x = [0.0, -13.7] },
    { name = "-136", x = [0.0, -13.6] },
    { name = "-135", x = [0.0, -13.5] },
    { name = "-134", x = [0.0, -13.4] },
    { name = "-133", x = [0.0, -13.3] },
    { name = "-132", x = [0.0, -13.2] },
    { name = "-131", x = [0.0, -13.1] },
    { name = "-130", x = [0.0, -13.0] },
    { name = "-129", x = [0.0, -12.9] },
    { name = "-128", x = [0.0, -12.8] },
    { name = "-127", x = [0.0, -12.7] },
    { name = "-126", x = [0.0, -12.6] },
    { name = "-125", x = [0.0, -12.5] },
    { name = "-124", x = [0.0, -12.4] },
    { name = "-123", x = [0.0, -12.3] },
    { name = "-122", x = [0.0, -12.2] },
    { name = "-121", x = [0.0, -12.1] },
    { name = "-120", x = [0.0, -12.0] },
    { name = "-119", x = [0.0, -11.9] },
    { name = "-118", x = [0.0, -11.8] },
    { name = "-117", x = [0.0, -11.7] },
    { name = "-116", x = [0.0, -11.6] },
    { name = "-115", x = [0.0, -11.5] },
    { name = "-114", x = [0.0, -11.4] },
    { name = "-113", x = [0.0, -11.3] },
    { name = "-112", x = [0.0, -11.2] },
    { name = "-111", x = [0.0, -11.1] },
    { name = "-110", x = [0.0, -11.0] },
    { name = "-109", x = [0.0, -10.9] },
    { name = "-108", x = [0.0, -10.8] },
    { name = "-107", x = [0.0, -10.7] },
    { name = "-106", x = [0.0, -10.6] },
    { name = "-105", x = [0.0, -10.5] },
    { name = "-104", x = [0.0, -10.4] },
    { name = "-103", x = [0.0, -10.3] },
    { name = "-102", x = [0.0, -10.2] },
    { name = "-101", x = [0.0, -10.1] },
    { name = "-100", x = [0.0, -10.0] },
    { name = "-99", x = [0.0, -9.9] },
    { name = "-98", x = [0.0, -9.8] },
    { name = "-97", x = [0.0, -9.7] },
    { name = "-96", x = [0.0, -9.6] },
    { name = "-95", x = [0.0, -9.5] },
    { name = "-94", x = [0.0, -9.4] },
    { name = "-93", x = [0.0, -9.3] },
    { name = "-92", x = [0.0, -9.2] },
    { name = "-91", x = [0.0, -9.1] },
    { name = "-90", x = [0.0, -9.0] },
    { name = "-89", x = [0.0, -8.9] },
    { name = "-88", x = [0.0, -8.8] },
    { name = "-87", x = [0.0, -8.7] },
    { name = "-86", x = [0.0, -8.6] },
    { name = "-85", x = [0.0, -8.5] },
    { name = "-84", x = [0.0, -8.4] },
    { name = "-83", x = [0.0, -8.3] },
    { name = "-82", x = [0.0, -8.2] },
    { name = "-81", x = [0.0, -8.1] },
    { name = "-80", x = [0.0, -8.0] },
    { name = "-79", x = [0.0, -7.9] },
    { name = "-78", x = [0.0, -7.8] },
    { name = "-77", x = [0.0, -7.7] },
    { name = "-76", x = [0.0, -7.6] },
    { name = "-75", x = [0.0, -7.5] },
    { name = "-74", x = [0.0, -7.4] },
    { name = "-73", x = [0.0, -7.3] },
    { name = "-72", x = [0.0, -7.2] },
    { name = "-71", x = [0.0, -7.1] },
    { name = "-70", x = [0.0, -7.0] },
    { name = "-69", x = [0.0, -6.9] },
    { name = "-68", x = [0.0, -6.8] },
    { name = "-67", x = [0.0, -6.7] },
    { name = "-66", x = [0.0, -6.6] },
    { name = "-65", x = [0.0, -6.5] },
    { name = "-64", x = [0.0, -6.4] },
    { name = "-63", x = [0.0, -6.3] },
    { name = "-62", x = [0.0, -6.2] },
    { name = "-61", x = [0.0, -6.1] },
    { name = "-60", x = [0.0, -6.0] },
    { name = "-59", x = [0.0, -5.9] },
    { name = "-58", x = [0.0, -5.8] },
    { name = "-57", x = [0.0, -5.7] },
    { name = "-56", x = [0.0, -5.6] },
    { name = "-55", x = [0.0, -5.5] },
    { name = "-54", x = [0.0, -5.4] },
    { name = "-53", x = [0.0, -5.3] },
    { name = "-52", x = [0.0, -5.2] },
    { name = "-51", x = [0.0, -5.1] },
    { name = "-50", x = [0.0, -5.0] },
    { name = "-49", x = [0.0, -4.9] },
    { name = "-48", x = [0.0, -4.8] },
    { name = "-47", x = [0.0, -4.7] },
    { name = "-46", x = [0.0, -4.6] },
    { name = "-45", x = [0.0, -4.5] },
    { name = "-44", x = [0.0, -4.4] },
    { name = "-43", x = [0.0, -4.3] },
    { name = "-42", x = [0.0, -4.2] },
    { name = "-41", x = [0.0, -4.1] },
    { name = "-40", x = [0.0, -4.0] },
    { name = "-39", x = [0.0, -3.9] },
    { name = "-38", x = [0.0, -3.8] },
    { name = "-37", x = [0.0, -3.7] },
    { name = "-36", x = [0.0, -3.6] },
    { name = "-35", x = [0.0, -3.5] },
    { name = "-34", x = [0.0, -3.4] },
    { name = "-33", x = [0.0, -3.3] },
    { name = "-32", x = [0.0, -3.2] },
    { name = "-31", x = [0.0, -3.1] },
    { name = "-30", x = [0.0, -3.0] },
    { name = "-29", x = [0.0, -2.9] },
    { name = "-28", x = [0.0, -2.8] },
    { name = "-27", x = [0.0, -2.7] },
    { name = "-26", x = [0.0, -2.6] },
    { name = "-25", x = [0.0, -2.5] },
    { name = "-24", x = [0.0, -2.4] },
    { name = "-23", x = [0.0, -2.3] },
    { name = "-22", x = [0.0, -2.2] },
    { name = "-21", x = [0.0, -2.1] },
    { name = "-20", x = [0.0, -2.0] },
    { name = "-19", x = [0.0, -1.9] },
    { name = "-18", x = [0.0, -1.8] },
    { name = "-17", x = [0.0, -1.7] },
    { name = "-16", x = [0.0, -1.6] },
    { name = "-15", x = [0.0, -1.5] },
    { name = "-14", x = [0.0, -1.4] },
    { name = "-13", x = [0.0, -1.3] },
    { name = "-12", x = [0.0, -1.2] },
    { name = "-11", x = [0.0, -1.1] },
    { name = "-10", x = [0.0, -1.0] },
    { name = "-09", x = [0.0, -0.9] },
    { name = "-08", x = [0.0, -0.8] },
    { name = "-07", x = [0.0, -0.7] },
    { name = "-06", x = [0.0, -0.6] },
    { name = "-05", x = [0.0, -0.5] },
    { name = "-04", x = [0.0, -0.4] },
    { name = "-03", x = [0.0, -0.3] },
    { name = "-02", x = [0.0, -0.2] },
    { name = "-01", x = [0.0, -0.1] },
    { name = "+00", x = [0.0, 0.0] },
    { name = "+01", x = [0.0, 0.1] },
    { name = "+02", x = [0.0, 0.2] },
    { name = "+03", x = [0.0, 0.3] },
    { name = "+04", x = [0.0, 0.4] },
    { name = "+05", x = [0.0, 0.5] },
    { name = "+06", x = [0.0, 0.6] },
    { name = "+07", x = [0.0, 0.7] },
    { name = "+08", x = [0.0, 0.8] },
    { name = "+09", x = [0.0, 0.9] },
    { name = "+10", x = [0.0, 1.0] },
    { name = "+11", x = [0.0, 1.1] },
    { name = "+12", x = [0.0, 1.2] },
    { name = "+13", x = [0.0, 1.3] },
    { name = "+14", x = [0.0, 1.4] },
    { name = "+15", x = [0.0, 1.5] },
    { name = "+16", x = [0.0, 1.6] },
    { name = "+17", x = [0.0, 1.7] },
    { name = "+18", x = [0.0, 1.8] },
    { name = "+19", x = [0.0, 1.9] },
    { name = "+20", x = [0.0, 2.0] },
    { name = "+21", x = [0.0, 2.1] },
    { name = "+22", x = [0.0, 2.2] },
    { name = "+23", x = [0.0, 2.3] },
    { name = "+24", x = [0.0, 2.4] },
    { name = "+25", x = [0.0, 2.5] },
    { name = "+26", x = [0.0, 2.6] },
    { name = "+27", x = [0.0, 2.7] },
    { name = "+28", x = [0.0, 2.8] },
    { name = "+29", x = [0.0, 2.9] },
    { name = "+30", x = [0.0, 3.0] },
    { name = "+31", x = [0.0, 3.1] },
    { name = "+32", x = [0.0, 3.2] },
    { name = "+33", x = [0.0, 3.3] },
    { name = "+34", x = [0.0, 3.4] },
    { name = "+35", x = [0.0, 3.5] },
    { name = "+36", x = [0.0, 3.6] },
    { name = "+37", x = [0.0, 3.7] },
    { name = "+38", x = [0.0, 3.8] },
    { name = "+39", x = [0.0, 3.9] },
    { name = "+40", x = [0.0, 4.0] },
    { name = "+41", x = [0.0, 4.1] },
    { name = "+42", x = [0.0, 4.2] },
    { name = "+43", x = [0.0, 4.3] },
    { name = "+44", x = [0.0, 4.4] },
    { name = "+45", x = [0.0, 4.5] },
    { name = "+46", x = [0.0, 4.6] },
    { name = "+47", x = [0.0, 4.7] },
    { name = "+48", x = [0.0, 4.8] },
    { name = "+49", x = [0.0, 4.9] },
    { name = "+50", x = [0.0, 5.0] },
    { name = "+51", x = [0.0, 5.1] },
    { name = "+52", x = [0.0, 5.2] },
    { name = "+53", x = [0.0, 5.3] },
    { name = "+54", x = [0.0, 5.4] },
    { name = "+55", x = [0.0, 5.5] },
    { name = "+56", x = [0.0, 5.6] },
    { name = "+57", x = [0.0, 5.7] },
    { name = "+58", x = [0.0, 5.8] },
    { name = "+59", x = [0.0, 5.9] },
    { name = "+60", x = [0.0, 6.0] },
    { name = "+61", x = [0.0, 6.1] },
    { name = "+62", x = [0.0, 6.2] },
    { name = "+63", x = [0.0, 6.3] },
    { name = "+64", x = [0.0, 6.4] },
    { name = "+65", x = [0.0, 6.5] },
    { name = "+66", x = [0.0, 6.6] },
    { name = "+67", x = [0.0, 6.7] },
    { name = "+68", x = [0.0, 6.8] },
    { name = "+69", x = [0.0, 6.9] },
    { name = "+70", x = [0.0, 7.0] },
    { name = "+71", x = [0.0, 7.1] },
    { name = "+72", x = [0.0, 7.2] },
    { name = "+73", x = [0.0, 7.3] },
    { name = "+74", x = [0.0, 7.4] },
    { name = "+75", x = [0.0, 7.5] },
    { name = "+76", x = [0.0, 7.6] },
    { name = "+77", x = [0.0, 7.7] },
    { name = "+78", x = [0.0, 7.8] },
    { name = "+79", x = [0.0, 7.9] },
    { name = "+80", x = [0.0, 8.0] },
    { name = "+81", x = [0.0, 8.1] },
    { name = "+82", x = [0.0, 8.2] },
    { name = "+83", x = [0.0, 8.3] },
    { name = "+84", x = [0.0, 8.4] },
    { name = "+85", x = [0.0, 8.5] },
    { name = "+86", x = [0.0, 8.6] },
    { name = "+87", x = [0.0, 8.7] },
    { name = "+88", x = [0.0, 8.8] },
    { name = "+89", x = [0.0, 8.9] },
    { name = "+90", x = [0.0, 9.0] },
    { name = "+91", x = [0.0, 9.1] },
    { name = "+92", x = [0.0, 9.2] },
    { name = "+93", x = [0.0, 9.3] },
    { name = "+94", x = [0.0, 9.4] },
    { name = "+95", x = [0.0, 9.5] },
    { name = "+96", x = [0.0, 9.6] },
    { name = "+97", x = [0.0, 9.7] },
    { name = "+98", x = [0.0, 9.8] },
    { name = "+99", x = [0.0, 9.9] },
    { name = "+100", x = [0.0, 10.0] },
    { name = "+101", x = [0.0, 10.1] },
    { name = "+102", x = [0.0, 10.2] },
    { name = "+103", x = [0.0, 10.3] },
    { name = "+104", x = [0.0, 10.4] },
    { name = "+105", x = [0.0, 10.5] },
    { name = "+106", x = [0.0, 10.6] },
    { name = "+107", x = [0.0, 10.7] },
    { name = "+108", x = [0.0, 10.8] },
    { name = "+109", x = [0.0, 10.9] },
    { name = "+110", x = [0.0, 11.0] },
    { name = "+111", x = [0.0, 11.1] },
    { name = "+112", x = [0.0, 11.2] },
    { name = "+113", x = [0.0, 11.3] },
    { name = "+114", x = [0.0, 11.4] },
    { name = "+115", x = [0.0, 11.5] },
    { name = "+116", x = [0.0, 11.6] },
    { name = "+117", x = [0.0, 11.7] },
    { name = "+118", x = [0.0, 11.8] },
    { name = "+119", x = [0.0, 11.9] },
    { name = "+120", x = [0.0, 12.0] },
    { name = "+121", x = [0.0, 12.1] },
    { name = "+122", x = [0.0, 12.2] },
    { name = "+123", x = [0.0, 12.3] },
    { name = "+124", x = [0.0, 12.4] },
    { name = "+125", x = [0.0, 12.5] },
    { name = "+126", x = [0.0, 12.6] },
    { name = "+127", x = [0.0, 12.7] },
    { name = "+128", x = [0.0, 12.8] },
    { name = "+129", x = [0.0, 12.9] },
    { name = "+130", x = [0.0, 13.0] },
    { name = "+131", x = [0.0, 13.1] },
    { name = "+132", x = [0.0, 13.2] },
    { name = "+133", x = [0.0, 13.3] },
    { name = "+134", x = [0.0, 13.4] },
    { name = "+135", x = [0.0, 13.5] },
    { name = "+136", x = [0.0, 13.6] },
    { name = "+137", x = [0.0, 13.7] },
    { name = "+138", x = [0.0, 13.8] },
    { name = "+139", x = [0.0, 13.9] },
    { name = "+140", x = [0.0, 14.0] },
    { name = "+141", x = [0.0, 14.1] },
    { name = "+142", x = [0.0, 14.2] },
    { name = "+143", x = [0.0, 14.3] },
    { name = "+144", x = [0.0, 14.4] },
    { name = "+145", x = [0.0, 14.5] },
    { name = "+146", x = [0.0, 14.6] },
    { name = "+147", x = [0.0, 14.7] },
    { name = "+148", x = [0.0, 14.8] },
    { name = "+149", x = [0.0, 14.9] },
    { name = "+150", x = [0.0, 15.0] },
    { name = "+151", x = [0.0, 15.1] },
    { name = "+152", x = [0.0, 15.2] },
    { name = "+153", x = [0.0, 15.3] },
    { name = "+154", x = [0.0, 15.4] },
    { name = "+155", x = [0.0, 15.5] },
    { name = "+156", x = [0.0, 15.6] },
    { name = "+157", x = [0.0, 15.7] },
    { name = "+158", x = [0.0, 15.8] },
    { name = "+159", x = [0.0, 15.9] },
    { name = "+160", x = [0.0, 16.0] },
    { name = "+161", x = [0.0, 16.1] },
    { name = "+162", x = [0.0, 16.2] },
    { name = "+163", x = [0.0, 16.3] },
    { name = "+164", x = [0.0, 16.4] },
    { name = "+165", x = [0.0, 16.5] },
    { name = "+166", x = [0.0, 16.6] },
    { name = "+167", x = [0.0, 16.7] },
    { name = "+168", x = [0.0, 16.8] },
    { name = "+169", x = [0.0, 16.9] },
    { name = "+170", x = [0.0, 17.0] },
    { name = "+171", x = [0.0, 17.1] },
    { name = "+172", x = [0.0, 17.2] },
    { name = "+173", x = [0.0, 17.3] },
    { name = "+174", x = [0.0, 17.4] },
    { name = "+175", x = [0.0, 17.5] },
    { name = "+176", x = [0.0, 17.6] },
    { name = "+177", x = [0.0, 17.7] },
    { name = "+178", x = [0.0, 17.8] },
    { name = "+179", x = [0.0, 17.9] },
    { name = "+180", x = [0.0, 18.0] },
    { name = "+181", x = [0.0, 18.1] },
    { name = "+182", x = [0.0, 18.2] },
    { name = "+183", x = [0.0, 18.3] },
    { name = "+184", x = [0.0, 18.4] },
    { name = "+185", x = [0.0, 18.5] },
    { name = "+186", x = [0.0, 18.6] },
    { name = "+187", x = [0.0, 18.7] },
    { name = "+188", x = [0.0, 18.8] },
    { name = "+189", x = [0.0, 18.9] },
    { name = "+190", x = [0.0, 19.0] },
    { name = "+191", x = [0.0, 19.1] },
    { name = "+192", x = [0.0, 19.2] },
    { name = "+193", x = [0.0, 19.3] },
    { name = "+194", x = [0.0, 19.4] },
    { name = "+195", x = [0.0, 19.5] },
    { name = "+196", x = [0.0, 19.6] },
    { name = "+197", x = [0.0, 19.7] },
    { name = "+198", x = [0.0, 19.8] },
    { name = "+199", x = [0.0, 19.9] },
    { name = "+200", x = [0.0, 20.0] }
]