resolution = 0.125
type = "poisson"
lib = "singular.lua"
scenario = "singular"

[generate_mesh]
intercepts = [
    [-1, 1],
    [-1, 1]
]
bcs = [
    [{bc = "d", plane = 0}, {bc = "d", plane = 1}],
    [{bc = "d", plane = 0}, {bc = "d", plane = 1}]
]

