-include /home/jyun/softwares/petsc-3.13.6/petscdir.mk
CFLAGS          =
FFLAGS          =
CPPFLAGS        =
FPPFLAGS        =
LOCDIR          = /home/jyun/Tandem/read_time
MANSEC          = TS
DIRS            = phasefield advection-diffusion-reaction eimex power_grid network multirate optimal_control
CLEANFILES      = TS-data-*

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
