name: Build and Test Tandem

on:
  workflow_call:
    inputs:
      petsc_version:
        required: true
        type: string
      dependencies_image:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler:
          - cc: gcc-13
            cxx: g++-13
          - cc: clang-18
            cxx: clang++-18
        dimension: [2, 3]
        degree: [3]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull dependencies image
        run: docker pull ${{ inputs.dependencies_image }}:${{ inputs.petsc_version }}

      - name: Build Tandem
        run: |
          IMAGE=${{ inputs.dependencies_image }}:${{ inputs.petsc_version }}
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e CC=${{ matrix.compiler.cc }} \
            -e CXX=${{ matrix.compiler.cxx }} \
            --user tandem \
            $IMAGE \
            bash -c "
              set -e
              sudo update-alternatives --install /usr/bin/cc cc /usr/bin/\$CC 100
              sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/\$CXX 100

              mkdir -p build_${{ matrix.dimension }}d_p${{ matrix.degree }} && cd build_${{ matrix.dimension }}d_p${{ matrix.degree }}
              cmake .. -DCMAKE_PREFIX_PATH=/opt/petsc \
                      -DWITH_PYTEST=ON \
                      -DDOMAIN_DIMENSION=${{ matrix.dimension }} \
                      -DPOLYNOMIAL_DEGREE=${{ matrix.degree }} \
                      -DCMAKE_C_COMPILER=\$CC \
                      -DCMAKE_CXX_COMPILER=\$CXX
              make -j$(nproc)"

      - name: Generate Reference Outputs
        run: |
          IMAGE=${{ inputs.dependencies_image }}:${{ inputs.petsc_version }}
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app/test/test_data/reference_configs \
            --user tandem \
            $IMAGE \
            bash -c "
              set -e
              if [ '${{ matrix.dimension }}' = '2' ]; then
                gmsh -2 circular_hole.geo
                /app/build_2d_p3/app/static circular_hole.toml \
                  --resolution 0.8 \
                  --matrix_free yes \
                  --mg_strategy twolevel \
                  --mg_coarse_level 1 \
                  --output /app/test/test_data/reference_results/output2D \
                  --petsc -options_file mg_cheby.cfg
                for i in 1 2 4 8; do
                  mpirun -np --oversubscribe $i /app/build_3d_p3/app/static circular_hole.toml \
                    --resolution 0.8 --matrix_free yes --mg_strategy twolevel \
                    --mg_coarse_level 1 --output /app/test/test_data/reference_results/output2D_$i \
                    --petsc -options_file mg_cheby.cfg
                done
                gmsh -2 bp1_ref.geo
                /app/build_2d_p3/app/tandem bp1_ref_QD.toml \
                  --petsc -options_file solver.cfg  > /app/log_SEAS_QD _${{ matrix.dimension }}d_p${{ matrix.degree }}_${{ matrix.compiler.cc }}>&1
                /app/build_2d_p3/app/tandem bp1_ref_QDGreen.toml \
                  --petsc -options_file solver.cfg > /app/log_SEAS_QDGreen _${{ matrix.dimension }}d_p${{ matrix.degree }}_${{ matrix.compiler.cc }}>&1
                
              else
                gmsh -3 spherical_hole.geo
                /app/build_3d_p3/app/static spherical_hole.toml \
                  --resolution 0.8 \
                  --matrix_free yes \
                  --mg_strategy twolevel \
                  --mg_coarse_level 1 \
                  --output /app/test/test_data/reference_results/output3D \
                  --petsc -options_file mg_cheby.cfg
                for i in 1 2 4 8; do
                  mpirun -np --oversubscribe $i /app/build_3d_p3/app/static spherical_hole.toml \
                    --resolution 0.8 --matrix_free yes --mg_strategy twolevel \
                    --mg_coarse_level 1 --output /app/test/test_data/reference_results/output3D_$i \
                    --petsc -options_file mg_cheby.cfg
                done
              fi"

      - name: Run Tests
        run: |
          IMAGE=${{ inputs.dependencies_image }}:${{ inputs.petsc_version }}
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app/build_${{ matrix.dimension }}d_p${{ matrix.degree }} \
            --user tandem \
            $IMAGE \
            make test

      - name: Rename doctest log
        if: always()
        run: |
          mv "${{ github.workspace }}/build_${{ matrix.dimension }}d_p${{ matrix.degree }}/Testing/Temporary/LastTest.log" \
            "${{ github.workspace }}/build_${{ matrix.dimension }}d_p${{ matrix.degree }}/Testing/Temporary/LastTest_${{ matrix.dimension }}d_p${{ matrix.degree }}_${{ matrix.compiler.cc }}.log"

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.dimension }}d-p${{ matrix.degree }}-${{ matrix.compiler.cc }}
          path: |
            ${{ github.workspace }}/build_${{ matrix.dimension }}d_p${{ matrix.degree }}/Testing/Temporary/LastTest_${{ matrix.dimension }}d_p${{ matrix.degree }}_${{ matrix.compiler.cc }}.log
            ${{ github.workspace }}/log_SEAS_QD_${{ matrix.dimension }}d_p${{ matrix.degree }}_${{ matrix.compiler.cc }}
            ${{ github.workspace }}/log_SEAS_QDGreen_${{ matrix.dimension }}d_p${{ matrix.degree }}_${{ matrix.compiler.cc }}
