name: tandem-build

on:
  pull_request:
    branches:
      - '*'
      - main

permissions:
  contents: read
  packages: write
  actions: read
  id-token: write  # Add this if needed
  checks: write    # Add this if needed



jobs:
  check-petsc-version:
    runs-on: ubuntu-24.04
    outputs:
      petsc_version: ${{ steps.get-current-version.outputs.version }}
      needs_rebuild: ${{ steps.check-version.outputs.rebuild }}
      dependencies_image: ${{ steps.check-version.outputs.dependencies_image }}
      tandem_image: ${{ steps.check-version.outputs.tandem_image }}
    steps:
      - name: Get Current PETSc Version
        id: get-current-version
        run: |
          VERSION=$(curl -s https://pypi.org/pypi/petsc/json | jq -r '.info.version')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Check if versioned image exists
        id: check-version
        run: |
          IMAGE_TAG=${{ steps.get-current-version.outputs.version }}
          # Convert repository to lowercase
          REPO_NAME=${{ github.repository }}
          REPO_NAME_LOWER=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          TANDEM_IMAGE="ghcr.io/${REPO_NAME_LOWER}/tandem-build"
          DEPENDENCIES_IMAGE="ghcr.io/${REPO_NAME_LOWER}/tandem-dependencies"
          DEPENDENCIES_IMAGE_NO_GHCR="${REPO_NAME_LOWER}/tandem-dependencies"
          echo "dependencies_image=${DEPENDENCIES_IMAGE}" >> $GITHUB_OUTPUT
          echo "tandem_image=${TANDEM_IMAGE}" >> $GITHUB_OUTPUT
          # Check if the image exists using GHCR API
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            "https://ghcr.io/v2/${DEPENDENCIES_IMAGE_NO_GHCR}/manifests/${IMAGE_TAG}")
          echo $STATUS_CODE
          if [ "$STATUS_CODE" -eq 200 ]; then
            echo "rebuild=false" >> $GITHUB_OUTPUT
          else
            echo "rebuild=true" >> $GITHUB_OUTPUT
          fi


  build-dependencies-image:
    needs: check-petsc-version
    if: needs.check-petsc-version.outputs.needs_rebuild == 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Delete existing image
        run: |
            # Get repository name in lowercase
            REPO_NAME_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            DEPENDENCIES_IMAGE_NO_GHCR="${REPO_NAME_LOWER}/tandem-dependencies"
            VERSION="${{ needs.check-petsc-version.outputs.petsc_version }}"
            
            # Delete existing image version if it exists
            curl -L -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/user/packages/container/${DEPENDENCIES_IMAGE_NO_GHCR}/versions/${VERSION}"
        continue-on-error: true

      - name: Build and push Dependencies Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: dependencies.Dockerfile 
          push: true
          tags: ${{ needs.check-petsc-version.outputs.dependencies_image }}:${{ needs.check-petsc-version.outputs.petsc_version }}
          platforms: linux/amd64
          build-args: |
              PETSC_VERSION=${{ needs.check-petsc-version.outputs.petsc_version }}
              CC=gcc-13
              CXX=g++-13

  build-and-push-tandem-image:
    needs: [check-petsc-version, build-dependencies-image]
    if: always() && !cancelled() && !failure()
    outputs:
      tandem_image_tag: ${{ steps.set-image-tag.outputs.image_tag }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - cc: gcc-13
            cxx: g++-13
          - cc: clang-18
            cxx: clang++-18
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set Image Tag
        id: set-image-tag
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            TAG="pr-${{ github.event.number }}"
          else
            TAG="latest"
          fi
          echo "image_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ needs.check-petsc-version.outputs.tandem_image }}:${{ steps.set-image-tag.outputs.image_tag }}-${{ matrix.compiler.cc }}
          platforms: linux/amd64
          build-args: |
            DEPENDENCIES_IMAGE=${{ needs.check-petsc-version.outputs.dependencies_image }}:${{ needs.check-petsc-version.outputs.petsc_version }}
            CC=${{ matrix.compiler.cc }}
            CXX=${{ matrix.compiler.cxx }}

  verify:
    needs: [build-and-push-tandem-image, check-petsc-version]
    if: success()
    runs-on: ubuntu-24.04 
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - cc: gcc-13
            cxx: g++-13
          - cc: clang-18
            cxx: clang++-18
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run Static Verification 2D
        run: |
          docker run --rm \
            ${{ needs.check-petsc-version.outputs.tandem_image }}:${{ needs.build-and-push-tandem-image.outputs.tandem_image_tag }}-${{ matrix.compiler.cc }} \
            -c "ulimit -Ss 65536 && cd examples/elasticity/2d && gmsh -2 circular_hole.geo"
          docker run --rm \
            ${{ needs.check-petsc-version.outputs.tandem_image }}:${{ needs.build-and-push-tandem-image.outputs.tandem_image_tag }}-${{ matrix.compiler.cc }} \
            -c "ulimit -Ss 65536 && cd examples/elasticity/2d && /app/build_2d_p3/app/static circular_hole.toml --resolution 0.8 --matrix_free yes --mg_strategy twolevel --mg_coarse_level 1 --petsc -options_file ../../options/mg_cheby.cfg"
      - name: Run Static Verification 3D
        run: |
          docker run --rm \
            ${{ needs.check-petsc-version.outputs.tandem_image }}:${{ needs.build-and-push-tandem-image.outputs.tandem_image_tag }}-${{ matrix.compiler.cc }} \
            -c "ulimit -Ss 65536 && cd examples/elasticity/3d && gmsh -3 spherical_hole.geo"
          docker run --rm \
            ${{ needs.check-petsc-version.outputs.tandem_image }}:${{ needs.build-and-push-tandem-image.outputs.tandem_image_tag }}-${{ matrix.compiler.cc }} \
            -c "ulimit -Ss 65536 && cd examples/elasticity/3d && /app/build_3d_p3/app/static spherical_hole.toml --resolution 0.8 --matrix_free yes --mg_strategy twolevel --mg_coarse_level 1 --petsc -options_file ../../options/mg_cheby.cfg"

