name: static-run

on:
  workflow_run:
    workflows: ["tandem-build"]
    types:
      - completed

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/tandem-build

jobs:
  run-static:
    runs-on: ubuntu-24.04
    steps:
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker Image
        run: docker pull $IMAGE_NAME:gcc-13

      - name: Run Static Inside Container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            $IMAGE_NAME:gcc-13 \
            /app/build/app/static /workspace/examples/elasticity/2d/circular_hole.toml \
            --resolution 0.8 --matrix_free yes --mg_strategy twolevel \
            --mg_coarse_level 1 --petsc -options_file /workspace/options/mg_cheby.cfg
